chore: update api-xsjs modules
SAP/xsk pull request #1186
Opened 2022-02-02 17:57 UTC by vmutafov

2022-02-02 18:56 UTC, d-velev commented
@vmutafov I've updated the `http.js` module in dirigible-labs, please refetch that. Removing the `getDestination` function from `net.js` is correct as it is not used.

2022-02-02 19:50 UTC, ThuF requested changes
It seems that these files are from older version, coming from DirigibleLabs

2022-02-08 09:02 UTC, vmutafov commented
@d-velev @ThuF could you check this PR again?

2022-02-08 09:07 UTC, ThuF approved these changes

2022-02-08 09:07 UTC, merged