Remove multiline comments from HDBProcedure and Function when getting their name
SAP/xsk pull request #1220
Opened 2022-02-08 09:11 UTC by d-velev

closes #1118

2022-02-08 09:15 UTC, BorisNen approved these changes
🥇

2022-02-09 08:23 UTC, ThuF commented on modules/engines/engine-hdb/src/main/java/com/sap/xsk/utils/XSKHDBUtils.java
> +    return content.replaceAll("(/\\*[^*]*\\*+(?:[^/*][^*]*\\*+)*/)|(--.*)", "").trim();
Could you extract the regex into `public static final String` variable

2022-02-09 08:24 UTC, ThuF requested changes
One minor comment to be addressed before merging the PR

2022-02-09 11:29 UTC, ThuF approved these changes

2022-02-09 11:29 UTC, merged