Stage release workflow
SAP/xsk pull request #1262
Opened 2022-02-14 10:32 UTC by krasimirdermendzhiev

**New**

* New workflow file stage release.

**Changed**

* Add call stage release from pre release.

2022-02-14 16:37 UTC, dpanayotov requested changes
The goal is to always upgrade to the new version without deleting anything

2022-02-15 15:54 UTC, krasimirdermendzhiev commented on .github/workflows/stage-release.yaml
> +        helm install xsk-stage xsk/xsk -n ${{ secrets.STAGE_NAMESPACE }} \
Yes. We can

2022-02-15 15:59 UTC, krasimirdermendzhiev commented on .github/workflows/stage-release.yaml
> +        helm uninstall xsk-stage -n ${{ secrets.STAGE_NAMESPACE }}
ok

2022-02-16 16:04 UTC, dpanayotov approved these changes

2022-02-16 19:38 UTC, ThuF approved these changes

2022-02-16 19:38 UTC, merged