Add properties for destinations in XSJS API
SAP/xsk pull request #1486
Opened 2022-03-28 07:49 UTC by d-velev

This PR makes it so that a destination wrapper object is returned in `getDestination`, in which we store host, port, pathPrefix and any other properties that the `cloudplatform.connectivity.Destination` object has (along with custom properties).

2022-03-31 14:43 UTC, MarinHadzhiev requested changes
Please replace sonar.sources property in the module pom with

<sonar.sources>src/main/resources/META-INF/dirigible/xsk,src/main/java/</sonar.sources>

so that also the java sources are analysed by the Sonar

2022-04-05 15:02 UTC, MarinHadzhiev reviewed
missing test for DestMailConfigProvider (that is why sonar check is failing)

2022-04-06 07:08 UTC, ThuF requested changes
Just few minor comments to be addressed before merging t he PR.

2022-04-06 07:08 UTC, ThuF commented on modules/api/api-xsjs/src/test/java/com/sap/xsk/api/test/CloudPlatformDestinationFacadeTest.java
> +  boolean isKymaFacadeSet = false;
Please use the `private` modifier

2022-04-06 07:08 UTC, ThuF commented on modules/engines/engine-mail-destination/pom.xml
> +    </dependency>
Not needed?

2022-04-06 07:08 UTC, ThuF commented on modules/engines/engine-mail-destination/src/test/java/com/sap/xsk/mail/test/DestMailConfigProviderTest.java
> +  MockedStatic<Configuration>configurationMock;
`private`?

2022-04-06 07:08 UTC, ThuF commented on modules/api/api-xsjs/src/main/java/com/sap/xsk/api/destination/Destination.java
> +  Destination(String host, int port, String pathPrefix, Properties properties) {
`public Destination(...)`?

2022-04-06 07:08 UTC, ThuF commented on modules/api/api-xsjs/src/main/resources/META-INF/dirigible/xsk/http/http.js
> +  var properties = JSON.parse(readDestination.getPropertiesAsJSON());
`let` instead of `var`?

2022-04-06 10:47 UTC, MarinHadzhiev approved these changes

2022-04-06 10:47 UTC, MarinHadzhiev commented on modules/engines/engine-mail-destination/src/test/java/com/sap/xsk/mail/test/DestMailConfigProviderTest.java
> +    props.setProperty("mail.user", "dirigible@eclipse.com");
change the user to something not related to OSS component

2022-04-08 08:53 UTC, ThuF approved these changes
Seems good to me

2022-04-08 08:55 UTC, merged