Server lite by including from Dirigible
SAP/xsk pull request #1697
Opened 2022-06-13 07:53 UTC by dimitarquanterall

XSK including minimum Dirigible modules.

2022-06-20 21:37 UTC, vmutafov requested changes

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +	<artifactId>xsk-server-lite-includes</artifactId>
Shouldn't the changes in this PR be the default ones and change `releng/server` to `releng/server-full` or something similar? Also, shouldn't these changes be applied to all other `releng` modules?

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +		<artifactId>xsk-releng-parent</artifactId>
Have you added a reference to this module in the parent `pom.xml`?

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +      <scope>compile</scope>
No need for explicit `compile` scope here

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +      <scope>compile</scope>
No need for explicit `compile` scope here

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +      <scope>compile</scope>
No need for explicit `compile` scope here

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +      <scope>compile</scope>
No need for explicit `compile` scope here

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +      <scope>compile</scope>
No need for explicit `compile` scope here

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +      <scope>compile</scope>
No need for explicit `compile` scope here

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +      <scope>compile</scope>
No need for explicit `compile` scope here

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +      <exclusions>
Is there a reason not to include specific dependencies instead of using exclusions?

2022-06-20 21:37 UTC, vmutafov commented on releng/server-lite-includes/pom.xml
> +<!--    <dependency>-->
Why is this commented out?

2022-06-20 22:31 UTC, vmutafov commented
@dimitarquanterall could you update this PR against the `main` branch and check if it's working as expected? On my machine, there seems to be a problem because I mostly got a blank screen when I opened XSK

2022-06-21 07:31 UTC, dimitarquanterall commented
Branch was updated agains `main` and everything seems to be working in Tomcat.

2022-07-14 09:21 UTC, vmutafov approved these changes

2022-07-19 06:25 UTC, vmutafov approved these changes

2022-07-19 06:25 UTC, merged