Runtime test for hdb-hdbti-simple sample
SAP/xsk pull request #1725
Opened 2022-06-23 12:50 UTC by aihanrashidov

Closes #1408 

- Made a simple fix on the hdbdd parser to allow `-` in the namespace.
- Modified the `hdb-hdbti-simple` sample by adding `xsjs` and `xsodata` files which would query the `Orders` table defined in the hdbdd. Also the files are used in an application test to confirm that the hdbdd and hdbti work properly.
- Modified the application integration tests to allow testing projects from the both the samples directory and the resources.
- Added the feature to make http and sql health checks on the deployed project when testing.
- Moved the hdb package from `engine-hdb` integration tests to `integration-tests-core` so the hana utils could be used from both the `applications` and `engine-hdb` integration tests.
- Added a method to execute http request without custom actions on future completion for `XSKHttpClient` in `integration-tests-core` module.

2022-06-24 08:36 UTC, ivanvolkoff approved these changes

2022-06-24 13:45 UTC, MarinHadzhiev requested changes

2022-06-24 13:45 UTC, MarinHadzhiev commented on integration-tests/applications/src/test/java/com/sap/xsk/integration/tests/applications/status/ProjectHealthChecker.java
> +        URL requestUrl = new URL(PROJECT_BASE_URI + endpointToCall);
this will not work with Kyma environment

2022-06-24 13:45 UTC, MarinHadzhiev commented on integration-tests/applications/src/test/java/com/sap/xsk/integration/tests/applications/status/ProjectHealthChecker.java
> +    PreparedStatement statement = connection.prepareStatement(TABLE_EXISTS_QUERY);
use try with resources for the prep stmt

2022-06-24 13:45 UTC, MarinHadzhiev commented on integration-tests/applications/src/test/java/com/sap/xsk/integration/tests/applications/status/ProjectHealthChecker.java
> +    PreparedStatement statement = connection.prepareStatement(TABLE_HAS_RECORDS_QUERY);
use try with resources for the prep stmt

2022-06-24 13:45 UTC, MarinHadzhiev commented on integration-tests/applications/src/test/java/com/sap/xsk/integration/tests/applications/status/ProjectHealthChecker.java
> +      throw new IOException("Retry limit reached!");
IllegalStateException is more appropriate in this case

2022-06-28 13:53 UTC, MarinHadzhiev approved these changes

2022-06-28 13:53 UTC, MarinHadzhiev commented on integration-tests/applications/src/test/java/com/sap/xsk/integration/tests/applications/status/ProjectHealthChecker.java
> +    ResultSet queryResult = statement.executeQuery();
put the result set inside try-with-resource

2022-06-29 07:32 UTC, MarinHadzhiev approved these changes

2022-06-29 11:44 UTC, merged