fix security api
SAP/xsk pull request #1780
Opened 2022-07-18 07:04 UTC by ivanvolkoff

This pr fixes security.crypto api.
Solves #1745 #1746

2022-07-18 07:15 UTC, vmutafov requested changes

2022-07-18 07:15 UTC, vmutafov commented on modules/api/api-xsjs/src/main/resources/META-INF/dirigible/xsk/security/security.js
> +exports.crypto = new XSCrypto;
This doesn't look right, add the braces in `new XSCrypto()`

2022-07-18 07:15 UTC, vmutafov commented on modules/api/api-xsjs/src/main/resources/META-INF/dirigible/xsk/security/security.js
> +		if (typeof data == 'object') {
Why are you type checking for `object`?

2022-07-19 07:16 UTC, vmutafov submitted a review, later dismissed

2022-08-01 12:14 UTC, dpanayotov commented
This issue is closed as the project is no longer maintained

2022-08-01 12:14 UTC, closed without merging