Map binary resultset to ArrayBuffer and test date mappings
SAP/xsk pull request #1782
Opened 2022-07-18 11:31 UTC by tdermendjiev

Implements https://github.com/SAP/xsk/issues/1736 and https://github.com/SAP/xsk/issues/1735

2022-07-20 12:01 UTC, vmutafov requested changes

2022-07-20 13:28 UTC, tdermendjiev commented on modules/api/api-xsjs/src/main/resources/META-INF/dirigible/xsk/hdb/hdbUtils.js
>          case "DATE":
As far as I tested it's a js date object.

2022-07-28 07:31 UTC, vmutafov approved these changes

2022-08-01 12:14 UTC, dpanayotov commented
This issue is closed as the project is no longer maintained

2022-08-01 12:14 UTC, closed without merging