test: selenium test setup
SAP/xsk pull request #455
Opened 2021-08-31 14:16 UTC by Fluctuationqt

2021-09-01 06:47 UTC, ThuF requested changes
Few minor comments

2021-09-01 06:47 UTC, ThuF commented on modules/integration-tests/pom.xml
> +      <version>${selenium.webdriver.manager.version}</version>
Test scope?

2021-09-01 06:47 UTC, ThuF commented on modules/integration-tests/pom.xml
> +      <version>${selenium.version}</version>
Test scope?

2021-09-01 06:47 UTC, ThuF commented on modules/integration-tests/pom.xml
> +    </profile>
Do we need this profile? Isn't the `integration-tests` profile enough?

2021-09-02 07:14 UTC, ThuF approved these changes
+1

2021-09-02 07:14 UTC, merged

2021-09-02 07:23 UTC, vmutafov commented
Related to: https://github.com/SAP/xsk/issues/382