chore: update migrations module
SAP/xsk pull request #969
Opened 2022-01-10 12:53 UTC by vmutafov

2022-01-10 14:33 UTC, ThuF requested changes
@vmutafov could you link which issue(s) this PR resolves?

2022-01-10 15:02 UTC, vmutafov commented
> @vmutafov could you link which issue(s) this PR resolves?

Sorry, I've hit an issue while testing the changes in this PR and forgot to mark this PR as Draft. I'm marking it now until I test locally with a newer Dirigible version having this PR https://github.com/eclipse/dirigible/pull/1420 . Once I finish validating the changes in the XSK PR, I'll link the appropriate issues.

2022-02-03 08:15 UTC, ThuF commented
Hi @vmutafov, it seems that the new Eclipse Dirigible (**6.1.21**) version was released and adopted in XSK. Should we merge the PR now and link the respective issues, or there are more things to be validated?

2022-02-07 14:37 UTC, ThuF approved these changes

2022-02-07 14:44 UTC, merged